#theme: jekyll-theme-minimal

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:            TAYA CHETRY
description:      Projects I am working on!
tagline:             'Particle Physicist * Experimentalist * Data Analyst'
description:         'Some small stuff!'
url:                 https://tchetry.github.io/
baseurl:             ''
paginate:            1
plugins:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed

# About/contact
author:
  name:              Taya Chetry
  url:               http://www.phy.ohio.edu/~chetry/
  email:             chetry@jlab.org
