#theme: jekyll-theme-minimal

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:            TAYA CHETRY
description:      Projects I am working on!
tagline:             'Particle Physicist * Experimentalist * Data Analyst'
description:         'Some small stuff!'
url:                 https://tchetry.github.io/
baseurl:             '/tchetry.github.io'
paginate:            5

# About/contact
author:
  name:              Taya Chetry
  url:               http://www.phy.ohiou.edu/~chetry/index.html
  email:             chetry@jlab.org
